research_task:
  description: >
    Research the given topic {topic} thoroughly to gather insights for creating engaging LinkedIn content.
  expected_output: >
    Comprehensive research findings about {topic} including key trends, statistics, and industry insigts.
  agent: research_agent

content_creation_task:
  description: >
    Review the context you got and create a compelling story about {topic} which is tailored 
    for the LinkedIn audience. Make sure to use emojis to make the post look more appealing.
  expected_output: >
    Create a LinkedIn post about {topic} that considers typical LinkedIn format and well-suited 
    emjois to emphasize your major points. Always start with provocative question or statement and
    thereafter provided clarity on the {topic}. 
    This size of the LinkedIn post should be between 200 and 300 words.
  agent: content_creation_agent

manager_task:
  description: >
    Review and improve the LinkedIn post. Ensure it meets these cirteria:
    1. Professional tone and language
    2. Clear value proposition
    3. Engaging storytelling structure
    4. Proper formatting and appropriate use of emojis for LinkedIn
    5. Strategic use of hashtags
    6. Call to action
    If any criteria are not met, revise the content accordingly.
  expected_output: >
    A LinkedIn post about {topic} that meets the all quality criteria mentioned in the description.
  agent: manager_agent
