research_task:
  description: >
    Research the given topic {topic} thoroughly to gather insights for creating engaging LinkedIn content.
  expected_output: >
    Comprehensive research findings about {topic} including key trends, statistics, and industry insigts.
  agent: research_agent

content_creation_task:
  description: >
    Create or revise LinkedIn content about {topic} based on:
    - Initial research findings
    - Specific feedback from the manager
    - LinkedIn best practices

  expected_output: >
    A well-crafted LinkedIn post that incorporates all feedback and requirements about {topic}.
    This size of the LinkedIn post should be between 200 and 300 words.
  agent: content_creation_agent

manager_task:
  description: >
    Review and improve the LinkedIn post. Ensure it meets these cirteria:
    1. Professional tone and language
    2. Clear value proposition
    3. Engaging storytelling structure
    4. Proper formatting and appropriate use of emojis for LinkedIn
    5. Strategic use of hashtags
    6. Call to action
    
    If improvements are needed:
    - Delegate specific revision tasks to the Content Creation Agent
    - Provide clear feedback on what needs to be improved
    - Review the revised content when it returns
  expected_output: >
    A final, polished LinkedIn post that meets all quality criteria about {topic}.
  agent: manager_agent
